# src/Stsbl/MailAliasBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        IServ\AdminBundle\EventListener\AdminMenuListenerInterface:
            tags:
              - { name: kernel.event_listener, event: iserv_portal.menu_admin, method: onBuildAdminMenu }

        IServ\CrudBundle\Crud\AbstractCrud:
            tags:
                - { name: iserv.crud }

    Stsbl\MailAliasBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Exception,Form/DataTransformer,Resources}'

    Stsbl\MailAliasBundle\Admin\AddressAdmin:
        arguments: [Stsbl\MailAliasBundle\Entity\Address]
        calls:
            - [setLogger, ["@iserv.logger"]] # LoggerTrait has no @required annotation on setter for now

    Stsbl\MailAliasBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
            
    Stsbl\MailAliasBundle\Validator\Constraints\AddressValidator:
        tags:
            - { name: validator.constraint_validator, alias: stsbl_mailalias_address_validator }

    Stsbl\MailAliasBundle\Validator\Constraints\NotAccountValidator:
        tags:
            - { name: validator.constraint_validator, alias: stsbl_mailalias_not_account_validator }

    Stsbl\MailAliasBundle\Validator\Constraints\SystemAddressValidator:
        tags:
            - { name: validator.constraint_validator, alias: stsbl_mailalias_system_address_validator }
