# src/Stsbl/MailRedirectionBundle/Resources/config/services.yml
services:
    stsbl.mailredrection.admin:
        class: Stsbl\MailRedirectionBundle\Admin\AddressAdmin # Our CRUD class
        arguments: [Stsbl\MailRedirectionBundle\Entity\Address]  # Sets the controlled entity class
        tags:
            - { name: iserv.crud } # Tells IServ about our CRUD
        calls:
            - [ setLogger, ["@iserv.logger"]]
            - [ setConfig, ["@iserv.config"]]
            
    stsbl.mailredrection.menu:
        class: Stsbl\MailRedirectionBundle\EventListener\MenuListener # Out MenuListener Class
        tags:
        #  - { name: kernel.event_listener, event: iserv_portal.menu_main, method: onBuildMainMenu } # Tells IServ about the main menu method
          - { name: kernel.event_listener, event: iserv_portal.menu_admin, method: onBuildAdminMenu } # Tells IServ about the admin menu method
          
    stsbl.mailredirection.form.group_recipient:
        class: Stsbl\MailRedirectionBundle\Form\Type\GroupRecipientType
        arguments: ["@iserv.config", "@doctrine.orm.entity_manager"]
        tags:
            - {name: form.type }
            
    stsbl.mailredirection.form.user_recipient:
        class: Stsbl\MailRedirectionBundle\Form\Type\UserRecipientType
        arguments: ["@iserv.config", "@doctrine.orm.entity_manager"]
        tags:
            - {name: form.type }
            
    stsbl.mailredirection.validator.address:
        class: Stsbl\MailRedirectionBundle\Validator\Constraints\AddressValidator
        arguments: ["@iserv.config", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: stsbl_mailredirection_address_validator }