services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\MailAliasBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Exception,Form/DataTransformer,Resources}'
