# src/Stsbl/MailAliasBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        IServ\AdminBundle\EventListener\AdminMenuListenerInterface:
            tags:
              - { name: kernel.event_listener, event: iserv_portal.menu_admin, method: onBuildAdminMenu }

    Stsbl\MailAliasBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Exception,Form/DataTransformer,Resources}'

    Stsbl\MailAliasBundle\Admin\AddressAdmin:
        arguments: [Stsbl\MailAliasBundle\Entity\Address]
        calls:
            - [setLogger, ["@iserv.logger"]] # LoggerTrait has no @required annotation on setter for now
